public class MyMain {
    public static void main(String[] args) {
        // MyArrayStack myStack = new MyArrayStack(3);
        // myStack.push(1);
        // myStack.push(2);
        // myStack.push(3);
        // myStack.Show();
        // myStack.pop();
        // myStack.Show();
        // myStack.pop();
        // myStack.Show();
        // myStack.pop();
        // myStack.Show();
        // MyArrayQueue myQueue = new MyArrayQueue(3);
        // myQueue.push(1);
        // myQueue.push(2);
        // myQueue.push(3);
        // myQueue.Show();
        // myQueue.pop();
        // myQueue.Show();
        // myQueue.pop();
        // myQueue.Show();
        // myQueue.pop();
        // myQueue.Show();
        // MyLinkedListStack stack = new MyLinkedListStack();
        // stack.push(1);
        // stack.Show();
        // stack.push(2);
        // stack.Show();
        // stack.push(3);
        // stack.Show();
        // stack.push(4);
        // stack.Show();
        // stack.pop();
        // stack.Show();
        // stack.pop();
        // stack.Show();
        // stack.pop();
        // stack.Show();
        MyLinkedListQueue queue = new MyLinkedListQueue();
        queue.push(1);
        queue.push(2);
        queue.push(3);
        queue.push(3);
        queue.push(3);
        queue.push(3);
        queue.push(3);
        queue.push(3);
        queue.Show();
        queue.pop();
        queue.pop();
        queue.pop();
        queue.Show();
        queue.pop();
        queue.Show();
    }
}
